name: happy_catering
description: flutter_final_project
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.15.4

  #bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #misc
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

  #self_created_packages
  user_repository:
    path: packages/user_repository
  meal_repository:
    path: packages/meal_repository
  order_repository:
    path: packages/order_repository
  firebase_storage: ^11.6.6

flutter:
  uses-material-design: true
  assets: 
    - assets/img/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
