// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZrNQK8nxleOdTjGHZSwpasL3WX22KZM',
    appId: '1:77141028901:web:ce8159a4e5339e515c0fcc',
    messagingSenderId: '77141028901',
    projectId: 'happycatering-f4f9d',
    authDomain: 'happycatering-f4f9d.firebaseapp.com',
    storageBucket: 'happycatering-f4f9d.appspot.com',
    measurementId: 'G-WL512JZQT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_7rLSDoXI3IITEoLnm-4OkD0BRucgBqw',
    appId: '1:77141028901:android:990b78832db8ada65c0fcc',
    messagingSenderId: '77141028901',
    projectId: 'happycatering-f4f9d',
    storageBucket: 'happycatering-f4f9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsPVtPBQLrcOhq0VhsToLZ8lhVstfuwQ',
    appId: '1:77141028901:ios:41d95f463a3327b05c0fcc',
    messagingSenderId: '77141028901',
    projectId: 'happycatering-f4f9d',
    storageBucket: 'happycatering-f4f9d.appspot.com',
    androidClientId: '77141028901-5mnbnk3sppaf8kqpb1pe0b3ft8tpv2g6.apps.googleusercontent.com',
    iosClientId: '77141028901-nm73jibqco1gqlnuuh2sgtna1po3nuns.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxsPVtPBQLrcOhq0VhsToLZ8lhVstfuwQ',
    appId: '1:77141028901:ios:559fac35feab5e725c0fcc',
    messagingSenderId: '77141028901',
    projectId: 'happycatering-f4f9d',
    storageBucket: 'happycatering-f4f9d.appspot.com',
    androidClientId: '77141028901-5mnbnk3sppaf8kqpb1pe0b3ft8tpv2g6.apps.googleusercontent.com',
    iosClientId: '77141028901-4dvheeur0m0n56gjcbqlulundr44iulh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
