name: order_repository
description: the repo that handles orders
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  cloud_firestore: ^4.15.4
  meal_repository:
    path: ../meal_repository

